# FOSSology Docker Compose file
# Copyright Siemens AG 2016, fabio.huser@siemens.com
# Copyright TNG Technology Consulting GmbH 2016-2017, maximilian.huber@tngtech.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Recipe for setting up a multi container FOSSology
#              Docker setup with separate Database instance
version: '3.5'
services:
  scheduler:
    image: fossology-scheduler:latest
    restart: unless-stopped
    user: "1001"
    environment:
      - FOSSOLOGY_DB_HOST=${DB_HOST}
      - FOSSOLOGY_DB_NAME=${DB_NAME}
      - FOSSOLOGY_DB_USER=${DB_USER}
      - FOSSOLOGY_DB_PASSWORD=${DB_PASSWORD}
      - FOSSOLOGY_CRON_START=false
      - FOSSOLOGY_CONF_REMOVE_DEFAULT_USER=${CONF_REMOVE_DEFAULT_USER}
      - FOSSOLOGY_CONF_BANNER_TEXT=${CONF_BANNER_TEXT}
      - FOSSOLOGY_CONF_SMTP_ENABLE=${CONF_SMTP_ENABLE}
      - FOSSOLOGY_CONF_SMTP_HOSTNAME=${CONF_SMTP_HOSTNAME}
      - FOSSOLOGY_CONF_SMTP_PORT=${CONF_SMTP_PORT}
      - FOSSOLOGY_CONF_SMTP_FROM=${CONF_SMTP_FROM}
      - FOSSOLOGY_CONF_SMTP_AUTH=${CONF_SMTP_AUTH}
      - FOSSOLOGY_CONF_SMTP_AUTH_USER=${CONF_SMTP_AUTH_USER}
      - FOSSOLOGY_CONF_SMTP_AUTH_PWD=${CONF_SMTP_AUTH_PWD}
      - FOSSOLOGY_CONF_SMTP_SSL_VERIFY=${CONF_SMTP_SSL_VERIFY}
      - FOSSOLOGY_CONF_SMTP_START_TLS=${CONF_SMTP_START_TLS}
      - FOSSOLOGY_CONF_PROXY_HTTP=${CONF_PROXY_HTTP}
      - FOSSOLOGY_CONF_PROXY_HTTPS=${CONF_PROXY_HTTPS}
      - FOSSOLOGY_CONF_PROXY_NONE=${CONF_PROXY_NONE}
    depends_on:
      - db
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 5s
      timeout: 5s
      retries: 2
  web:
    image: fossology-web:latest
    user: "1001"
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - FOSSOLOGY_SCHEDULER_HOST=scheduler
      - FOSSDASH_URL=http://influxdb:8086
      - FOSSOLOGY_CONF_WEB_APACHE_CONF_FILE=${CONF_WEB_APACHE_CONF_FILE}
      - FOSSOLOGY_CONF_WEB_APACHE_SECURITY_PATCH=${CONF_WEB_APACHE_SECURITY_PATCH}
    command: web
    ports:
      - 80:1880
    depends_on:
      - db
      - scheduler
    volumes:
      - repository:/srv/fossology/repository/
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf localhost/repo/api/v1/version || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: fossology-db:latest
    restart: unless-stopped
    environment:
      - POSTGRESQL_DB=fossology
      # Regular User & Password
      - POSTGRESQL_USER=fossy
      - POSTGRESQL_PASSWORD=fossy
      # Password for admin user 'postgres'
      - POSTGRESQL_POSTGRES_PASSWORD=yssof
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start-period: 10s

volumes:
  database:
  repository:
