apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: db
    app: fossology
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
      app: fossology
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: db
        app: fossology
    spec:
      containers:
        - name: db
          image: fossology:db
          imagePullPolicy: Always
          resources:
            requests: 
              memory: "240Mi"
              cpu: "50m"
            limits:
              memory: "350Mi"
              cpu: "200m"
          envFrom:
            - secretRef:
                name: database-secrets
          # livenessProbe:
          #  exec:
          #    command:
          #      - pg_isready --dbname $POSTGRESQL_DATABASE --username $POSTGRESQL_USERNAME
          #  failureThreshold: 5
          #  periodSeconds: 10
          #  timeoutSeconds: 5
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: database
      restartPolicy: Always
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database
      resources: {}
      volumeMounts:
        - name: database
          mountPath: /bitnami/postgresql
  imagePullSecrets:
    - name: gitlab-tech-registry
  triggers:
  - type: "ConfigChange"
