apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: repository
  name: repository
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-default-storage-class
  resources:
    requests:
      storage: "50Gi"
status: {}
