apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: scheduler
    app: fossology
  name: scheduler
spec:
  replicas: 1
  triggers:
    - type: "ConfigChange"
  selector:
    matchLabels:
      app: fossology
      component: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fossology
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: fossology:scheduler
          imagePullPolicy: Always
          resources:
            requests: 
              memory: "315Mi"
              cpu: "50m"
            limits:
              memory: "450Mi"
              cpu: "200m"
          env:
            - name: FOSSOLOGY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_DATABASE
            - name: FOSSOLOGY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: FOSSOLOGY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_USERNAME
            - name: FOSSOLOGY_CONF_EXTRA_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: fossology-config-map
                  key: extra-keywords
          envFrom:
            - configMapRef:
                name: fossology-global-config
            - configMapRef:
                name: proxy-config
            - configMapRef:
                name: fossology-backup-configmap
            - secretRef:
                name: fossology-backup-s3-secret
          livenessProbe:
            exec:
              command:
                - "true"
            failureThreshold: 2
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /srv/fossology/
              name: repository
      imagePullSecrets:
          - name: gitlab-tech-registry
      restartPolicy: Always
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: repository
status: {}
