apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: web 
    app: fossology
  name: web    
spec:
  replicas: 1
  triggers:
    - type: "ConfigChange"
  selector:
    matchLabels:
      app: fossology
      component: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fossology
        component: web
    spec:
      volume:
        - name: repository
          persistentVolumeClaim:
            claimName: repository
      containers:
        - name: web
          image: fossology:web
          imagePullPolicy: Always
          resources:
            requests: 
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "200m"
          env:
            - name: FOSSOLOGY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_DATABASE
            - name: FOSSOLOGY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: FOSSOLOGY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRESQL_USERNAME
            - name: FOSSOLOGY_SCHEDULER_HOST
              value: scheduler
            - name: FOSSOLOGY_CONF_WEB_APACHE_CONF_FILE
              valueFrom:
                configMapKeyRef:
                  name: fossology-config-map
                  key: apache-fossology.conf
            - name: FOSSOLOGY_CONF_EXTERNAL_AUTH
              valueFrom:
                configMapKeyRef:
                  name: fossology-config-map
                  key: external-auth.conf
          envFrom:
            - configMapRef:
                name: proxy-config
            - configMapRef:
                name: fossology-global-config
            - prefix: CONNECT_
              secretRef:
                name: connect-secret
          # livenessProbe:
          #  exec:
          #    command:
          #      - curl -sSf localhost/repo/api/v1/version || exit 1
          #  failureThreshold: 5
          #  periodSeconds: 5
          #  timeoutSeconds: 5
          ports:
            - containerPort: 1880
          volumeMounts:
            - mountPath: /srv/fossology/
              name: repository
      imagePullSecrets:
          - name: gitlab-tech-registry
      restartPolicy: Always
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: repository
  imagePullSecrets:
    - name: gitlab-tech-registry
